"""Medical-device industry knowledge seed data."""
from knowledge_base.models import KBType, normalize_record
INDUSTRY_RECORDS = [
 {"id":"mdr_34","title":"医疗器械监督管理条例第三十四条 委托生产","content":"医疗器械注册人、备案人可以自行生产医疗器械，也可以委托符合本条例规定、具备相应条件的企业生产医疗器械。委托生产医疗器械的，医疗器械注册人、备案人应当对所委托生产的医疗器械质量负责，并加强对受托生产企业生产行为的管理，保证其按照法定要求进行生产。医疗器械注册人、备案人应当与受托生产企业签订委托协议，明确双方权利、义务和责任。受托生产企业应当依照法律法规、医疗器械生产质量管理规范、强制性标准、产品技术要求和委托协议组织生产，对生产行为负责，并接受委托方的监督。具有高风险的植入性医疗器械不得委托生产，具体目录由国务院药品监督管理部门制定、调整并公布。","tags":["医疗器械","委托生产","质量协议","注册人"],"contract_types":["medical_device_commissioned_manufacturing"],"clause_dimensions":["主体资格","合法性合规性","履约能力"],"citation":"《医疗器械监督管理条例》第三十四条","source_url":"https://www.gov.cn/gongbao/content/2021/content_5595920.htm"},
 {"id":"mdr_44","title":"医疗器械监督管理条例第四十四条 经营质量管理体系","content":"从事医疗器械经营，应当依照法律法规和国务院药品监督管理部门制定的医疗器械经营质量管理规范的要求，建立健全与所经营医疗器械相适应的质量管理体系并保证其有效运行。","tags":["医疗器械","经营","质量管理体系","经营质量管理规范"],"contract_types":["medical_device_general","medical_device_commissioned_manufacturing"],"clause_dimensions":["主体资格","合法性合规性"],"citation":"《医疗器械监督管理条例》第四十四条","source_url":"https://www.gov.cn/gongbao/content/2021/content_5595920.htm"},
 {"id":"mdr_reg_008","title":"医疗器械注册与备案管理办法第八条 注册与备案分类管理","content":"第一类医疗器械实行产品备案管理。第二类、第三类医疗器械实行产品注册管理。境内第一类医疗器械备案，备案人向设区的市级负责药品监督管理的部门提交备案资料。境内第二类医疗器械由省、自治区、直辖市药品监督管理部门审查，批准后发给医疗器械注册证。境内第三类医疗器械由国家药品监督管理局审查，批准后发给医疗器械注册证。进口第一类医疗器械备案，备案人向国家药品监督管理局提交备案资料。进口第二类、第三类医疗器械由国家药品监督管理局审查，批准后发给医疗器械注册证。","tags":["医疗器械","注册管理","备案管理","分类管理","注册证"],"contract_types":["medical_device_general","medical_device_commissioned_manufacturing","technology_transfer"],"clause_dimensions":["主体资格","合法性合规性"],"citation":"《医疗器械注册与备案管理办法》（国家市场监督管理总局令第47号）第八条","source":"医疗器械注册与备案管理办法（国家市场监督管理总局令第47号）","article_or_clause":"第八条","category":"医疗器械监管·注册","authority_level":"regulation","source_url":"https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzbmgz/202111/t20211119_442087.html"},
 {"id":"mdr_prod_004","title":"医疗器械生产监督管理办法第四条 生产分类许可","content":"根据医疗器械风险程度，医疗器械生产实施分类管理。从事第二类、第三类医疗器械生产活动，应当经所在地省、自治区、直辖市药品监督管理部门批准，依法取得医疗器械生产许可证；从事第一类医疗器械生产活动，应当向所在地设区的市级负责药品监督管理的部门办理医疗器械生产备案。","tags":["医疗器械","生产许可","生产备案","分类管理","生产许可证"],"contract_types":["medical_device_commissioned_manufacturing","medical_device_general"],"clause_dimensions":["主体资格","合法性合规性","履约能力"],"citation":"《医疗器械生产监督管理办法》（国家市场监督管理总局令第53号）第四条","source":"医疗器械生产监督管理办法（国家市场监督管理总局令第53号）","article_or_clause":"第四条","category":"医疗器械监管·生产","authority_level":"regulation","source_url":"https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzbmgz/202305/t20230508_478335.html"},
 {"id":"mdr_prod_041","title":"医疗器械生产监督管理办法第四十一条 召回义务","content":"医疗器械注册人、备案人发现生产的医疗器械不符合强制性标准、经注册或者备案的产品技术要求，或者存在其他缺陷的，应当立即停止生产，通知相关经营企业、使用单位和消费者停止经营和使用，召回已经上市销售的医疗器械，采取补救、销毁等措施，记录相关情况，发布相关信息，并将医疗器械召回和处理情况向药品监督管理部门和卫生主管部门报告。受托生产企业应当按照医疗器械召回的相关规定履行责任，并协助医疗器械注册人、备案人对所生产的医疗器械实施召回。","tags":["医疗器械","召回义务","受托生产企业","停止生产","注册人","备案人"],"contract_types":["medical_device_commissioned_manufacturing"],"clause_dimensions":["合法性合规性","合同条款","履约能力"],"citation":"《医疗器械生产监督管理办法》（国家市场监督管理总局令第53号）第四十一条","source":"医疗器械生产监督管理办法（国家市场监督管理总局令第53号）","article_or_clause":"第四十一条","category":"医疗器械监管·生产","authority_level":"regulation","source_url":"https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzbmgz/202305/t20230508_478335.html"},
 {"id":"mdr_ops_004","title":"医疗器械经营监督管理办法第四条 经营分类管理","content":"按照医疗器械风险程度，医疗器械经营实施分类管理。经营第三类医疗器械实行许可管理，经营第二类医疗器械实行备案管理，经营第一类医疗器械不需要许可和备案。","tags":["医疗器械","经营许可","经营备案","分类管理"],"contract_types":["medical_device_general"],"clause_dimensions":["主体资格","合法性合规性"],"citation":"《医疗器械经营监督管理办法》（国家市场监督管理总局令第54号）第四条","source":"医疗器械经营监督管理办法（国家市场监督管理总局令第54号）","article_or_clause":"第四条","category":"医疗器械监管·经营","authority_level":"regulation","source_url":"https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzbmgz/202305/t20230508_478334.html"},
 {"id":"md_quality_001","title":"医疗器械生产监督管理办法第三十二条 委托生产质量协议与责任","content":"医疗器械注册人、备案人委托生产的，应当对受托方的质量保证能力和风险管理能力进行评估，按照国家药品监督管理局制定的委托生产质量协议指南要求，与其签订质量协议以及委托协议，监督受托方履行有关协议约定的义务。受托生产企业应当按照法律、法规、规章、医疗器械生产质量管理规范、强制性标准、产品技术要求、委托生产质量协议等要求组织生产，对生产行为负责，并接受医疗器械注册人、备案人的监督。","tags":["委托生产","质量协议","注册人","受托生产"],"contract_types":["medical_device_commissioned_manufacturing"],"clause_dimensions":["合法性合规性","合同条款","履约能力"],"citation":"《医疗器械生产监督管理办法》（国家市场监督管理总局令第53号）第三十二条","source":"医疗器械生产监督管理办法（国家市场监督管理总局令第53号）","article_or_clause":"第三十二条","category":"医疗器械监管·生产","authority_level":"regulation","source_url":"https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzbmgz/202305/t20230508_478335.html","review_status":"published"},
 {"id":"mdr_clinical_001","title":"医疗器械注册与备案管理办法第三十七条 临床试验备案与机构要求","content":"开展医疗器械临床试验，应当按照医疗器械临床试验质量管理规范的要求，在具备相应条件并按照规定备案的医疗器械临床试验机构内进行。临床试验开始前，临床试验申办者应当向所在地省、自治区、直辖市药品监督管理部门进行临床试验备案。临床试验医疗器械的生产应当符合医疗器械生产质量管理规范的相关要求。","tags":["临床试验","临床试验备案","申办者","临床机构"],"contract_types":["medical_device_general","technology_transfer"],"clause_dimensions":["合法性合规性","数据合规","履约能力"],"citation":"《医疗器械注册与备案管理办法》（国家市场监督管理总局令第47号）第三十七条","source":"医疗器械注册与备案管理办法（国家市场监督管理总局令第47号）","article_or_clause":"第三十七条","category":"医疗器械监管·注册","authority_level":"regulation","source_url":"https://www.moj.gov.cn/pub/sfbgw/flfggz/flfggzbmgz/202111/t20211119_442087.html","review_status":"published"}
]
def get_records():
    return [normalize_record(r, KBType.INDUSTRY.value, {"source_url":"https://www.nmpa.gov.cn/", "review_status":"published", "authority_level":"regulation"}) for r in INDUSTRY_RECORDS]
