"""Standard clause and template reference records."""
from knowledge_base.models import KBType, normalize_record
TEMPLATE_RECORDS = [
 {"id":"tpl_manufacturing_liability_001","title":"委托生产标准条款 质量与责任","content":"受托方应按照适用的医疗器械法规、质量管理规范及双方质量协议组织生产，对生产过程和产品质量承担相应责任，并配合注册人或备案人的监督、审计和召回安排。","tags":["委托生产","质量","召回","责任"],"contract_types":["medical_device_commissioned_manufacturing"],"clause_dimensions":["合法性合规性","履约能力","违约责任"],"authority_level":"standard_clause","replacement_clause":"受托方应按照适用法规、质量管理规范及双方质量协议组织生产，并承担约定的质量责任。"},
 {"id":"tpl_technology_ip_001","title":"成果转化标准条款 知识产权","content":"双方应分别列明背景知识产权和项目成果；项目成果的申请权、权利归属、许可实施、改进成果和技术资料交付以附件清单为准。","tags":["技术开发","成果转化","知识产权"],"contract_types":["technology_transfer"],"clause_dimensions":["标的客体","合同条款"],"authority_level":"standard_clause","replacement_clause":"双方应在附件中明确背景知识产权、项目成果、改进成果的归属、申请权、许可和交付安排。"},
 {"id":"tpl_general_dispute_001","title":"通用标准条款 争议解决","content":"因本合同引起或与本合同有关的争议，双方应先行协商；协商不成的，提交约定的仲裁机构仲裁或向有管辖权的人民法院提起诉讼，二者应择一明确。","tags":["争议解决","仲裁","诉讼"],"contract_types":["general","medical_device_commissioned_manufacturing","technology_transfer"],"clause_dimensions":["争议解决"],"authority_level":"standard_clause","replacement_clause":"协商不成的，任一方可向有管辖权的人民法院提起诉讼。"},

 # ---- 以下 3 条为缺口建议稿（标准条款参考），阈值【】待确认；
 # ---- 确认后替换为正式范本原文并改 published 才会进入检索 ----
 {"id":"tpl_payment_milestone_001","title":"委托生产标准条款 付款节点（建议稿）","content":"合同总价款分四期支付：（一）预付款，合同签订并经供方开具等额增值税专用发票后【10】个工作日内支付合同总额的【30%】；（二）里程碑款，按双方确认的生产进度节点（如首批样件下线、批量投产）分期支付至累计【70%】；（三）验收款，产品验收合格且双方签署验收单后【15】个工作日内支付至累计【90%】；（四）质保金，合同总额的【10%】于质保期届满且无未决质量争议后【10】个工作日内无息支付。供方逾期交付的，付款节点相应顺延；每期付款以收到合规发票为前提。","tags":["付款","里程碑","质保金","发票","委托生产","建议稿"],"contract_types":["medical_device_commissioned_manufacturing"],"clause_dimensions":["商业风险","合同条款"],"authority_level":"standard_clause","replacement_clause":"合同价款按预付款、里程碑款、验收款、质保金四期支付，比例与节点以附件约定为准。","status":"draft","review_status":"pending","draft_note":"比例【30/40/20/10】与发票要求待确认"},
 {"id":"tpl_rd_ip_001","title":"委托研发标准条款 知识产权归属（建议稿）","content":"（一）双方确认各自的背景知识产权归原权利方所有；一方为履行本合同使用对方背景知识产权的，仅限于履约目的。（二）甲方出资委托研发形成的技术成果（含专利申请权、技术秘密、软件著作权、技术资料）归甲方所有，乙方应在成果形成后【10】个工作日内移交全部技术资料并配合办理权利登记。（三）乙方在交付成果前已有的独立改进成果归乙方，但不得限制甲方对交付成果的使用。（四）未经甲方书面同意，乙方不得就本合同成果申请专利、发表论文或向第三方披露；双方可约定乙方享有署名及内部留存权利。","tags":["委托研发","知识产权","背景知识产权","论文发表","建议稿"],"contract_types":["technology_transfer"],"clause_dimensions":["标的客体","合同条款"],"authority_level":"standard_clause","replacement_clause":"委托研发成果及其知识产权归委托方所有，受托方移交技术资料并配合权利登记；背景知识产权各自保留，履约外使用须书面同意。","status":"draft","review_status":"pending","draft_note":"与 tpl_technology_ip_001 的区别是出资归属更明确；条款取向待确认"},
 {"id":"tpl_acceptance_001","title":"采购标准条款 验收与质保（建议稿）","content":"（一）验收依据：国家标准、行业标准、产品注册/备案技术要求及双方书面确认的技术协议。（二）验收流程：到货验收（数量、外观、包装、【7】个工作日内）→ 安装调试验收（需安装设备调试合格后双方签署）→ 试运行验收（连续稳定运行【90】日或按批次抽样检验）。（三）不合格处理：供方应在接到通知后【15】个工作日内修理、更换或重作，由此发生的费用由供方承担；逾期未处理或同一问题两次不合格的，采购方有权退货并要求赔偿。（四）质保期：自最终验收合格之日起不少于【12】个月；质保期内因产品本身质量原因产生的维修、更换费用由供方承担，供方应在【48】小时内响应。","tags":["验收","质保期","不合格处理","采购","建议稿"],"contract_types":["general","medical_device_general"],"clause_dimensions":["合同条款","履约能力","违约责任"],"authority_level":"standard_clause","replacement_clause":"验收依据国家/行业标准与技术协议，按到货、安装调试、试运行三段验收；不合格的限期修理更换，质保期自验收合格起算不少于12个月。","status":"draft","review_status":"pending","draft_note":"各时限【】与质保期长短待确认"}
]
def get_records():
    return [normalize_record(r, KBType.TEMPLATE.value, {"review_status": "pending", "status": "draft", "source": "标准合同范本参考（待评审确认）"}) for r in TEMPLATE_RECORDS]
